{{- if and (not .Values.api.existingUiClientSecret) .Values.api.UiClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "osb-api-ui-secret"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.api.UiClientSecret | b64enc | quote }}
{{- end }}
