{{- if and (not .Values.api.existingClientSecret) .Values.api.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "osb-api-secret"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.api.clientSecret | b64enc | quote }}
{{- end }}
