{{- if and (not .Values.mdrdb.stdImports.existingCdiscSecret) .Values.mdrdb.stdImports.cdiscSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "cdisc-secret"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.mdrdb.stdImports.cdiscSecret | b64enc | quote }}
{{- end }}
