{{- if .Values.consumerApi.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.consumerApi.fullnameOverride }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: "consumer-api"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.consumerApi.fullnameOverride }}
  minReplicas: {{ .Values.consumerApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.consumerApi.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.consumerApi.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.consumerApi.autoscaling.targetMemoryUtilizationPercentage }}
          type: Utilization
{{- end }}
