{{- if .Values.neo4j.ingress.enabled -}}
{{- $fullName := .Values.neo4j.fullnameOverride -}}
{{- $svcPort := .Values.neo4j.service.boltPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- if .Values.neo4j.ingress.router }}
    router: {{ .Values.neo4j.ingress.router }}
    {{- end }}
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.neo4j.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.neo4j.ingress.className }}
  ingressClassName: {{ .Values.neo4j.ingress.className }}
  {{- end }}
  {{- if .Values.neo4j.ingress.tls }}
  tls:
    {{- range .Values.neo4j.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName  }}
    {{- end }}
  {{- else }}
  tls:
  - {}
  {{- end }}
  rules:
    {{- range .Values.neo4j.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
