apiVersion: v1
kind: Secret
metadata:
  name: "neo4j-secret"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.neo4j.neo4j.password | b64enc | quote }}
