{{- if and (not .Values.neo4j.existingdsnApiSecret) .Values.neo4j.dsnApiSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "neo4j-dsn"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  dsn: {{ .Values.neo4j.dsnApiSecret | b64enc | quote }}
{{- end }}
