{{- if .Values.sb.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sb.fullnameOverride }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: "frontend"
spec:
  type: {{ .Values.sb.service.type }}
  ports:
    - port: {{ .Values.sb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "frontend"
{{- end }}
